workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    triggering:
      events:
        - push

    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build unsigned .app
        script: |
          flutter build ios \
            --release \
            --no-codesign

      - name: Archive .app to .xcarchive
        script: |
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -archivePath build/ios/Runner.xcarchive \
            BUILD_DIR=build/ios \
            CODE_SIGN_STYLE=Automatic \
            -allowProvisioningUpdates

      - name: Export signed .ipa
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath build/ios/Runner.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist ios/ExportOptions.plist \
            -allowProvisioningUpdates

    artifacts:
      - build/ios/ipa/*.ipa
